-- ============================================================================
-- BASELINE: Create tables if they don't exist (for fresh databases)
-- On production these already exist, so IF NOT EXISTS makes this idempotent
-- ============================================================================

-- Create enums (idempotent using DO blocks)
DO $$ BEGIN
    CREATE TYPE "public"."plan" AS ENUM ('free', 'premium', 'student');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    CREATE TYPE "public"."platform" AS ENUM ('YouTube', 'Vimeo');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    CREATE TYPE "public"."processing_mode" AS ENUM ('manual', 'auto');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    CREATE TYPE "public"."status" AS ENUM ('active', 'canceled', 'past_due', 'trialing', 'incomplete');
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

-- Create tables in dependency order
CREATE TABLE IF NOT EXISTS "users" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "email" text NOT NULL,
    "is_subscribed" boolean DEFAULT false NOT NULL,
    "monthly_video_count" smallint DEFAULT 0 NOT NULL,
    "last_reset_date" timestamp with time zone DEFAULT now() NOT NULL,
    "processsing_mode" "processing_mode" DEFAULT 'auto' NOT NULL,
    "stripe_customer_id" text,
    CONSTRAINT "users_stripe_customer_id_unique" UNIQUE ("stripe_customer_id")
);--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "videos" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "videos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
    "user_id" uuid NOT NULL,
    "platform" "platform" DEFAULT 'YouTube' NOT NULL,
    "title" text NOT NULL,
    "channel_name" text,
    "duration" integer,
    "category" text,
    "url" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "expiry_date" timestamp with time zone DEFAULT (now() + '7 days'::interval),
    "video_id" text,
    "description" text,
    "deleted_at" timestamp,
    "should_expire" boolean DEFAULT true NOT NULL
);--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "summaries" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "summaries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
    "video_id" bigint,
    "content" text DEFAULT '' NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "questions" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "questions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
    "video_id" bigint NOT NULL,
    "question_text" text NOT NULL,
    "question_type" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "question_options" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "question_options_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
    "question_id" bigint NOT NULL,
    "option_text" text NOT NULL,
    "is_correct" boolean NOT NULL,
    "order_index" smallint,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "explanation" text
);--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "user_answers" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
    "user_id" uuid NOT NULL,
    "question_id" bigint NOT NULL,
    "selected_option_id" bigint NOT NULL,
    "text_answer" text,
    "is_correct" boolean NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "user_question_progress" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_question_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
    "user_id" uuid NOT NULL,
    "question_id" bigint NOT NULL,
    "box_level" integer DEFAULT 1,
    "next_review_date" date,
    "times_correct" integer DEFAULT 0,
    "times_incorrect" integer DEFAULT 0,
    "last_reviewed_at" timestamp,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "user_question_progress_user_id_question_id_key" UNIQUE ("user_id", "question_id"),
    CONSTRAINT "user_question_progress_unique" UNIQUE ("user_id", "question_id")
);--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "extension_tokens" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL,
    "token" text NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "extension_tokens_token_key" UNIQUE ("token")
);--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "subscriptions" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
    "user_id" uuid,
    "stripe_customer_id" text,
    "stripe_subscription_id" text,
    "status" "status" DEFAULT 'active' NOT NULL,
    "plan" "plan" NOT NULL,
    "current_period_start" timestamp with time zone,
    "current_period_end" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    "cancel_at_period_end" boolean DEFAULT false NOT NULL,
    "canceled_at" timestamp with time zone
);--> statement-breakpoint

-- Create indexes (idempotent)
CREATE INDEX IF NOT EXISTS "idx_users_stripe_customer_id" ON "users" USING btree ("stripe_customer_id");--> statement-breakpoint

-- Create foreign keys (idempotent using DO blocks)
DO $$ BEGIN
    ALTER TABLE "videos" ADD CONSTRAINT "videos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "summaries" ADD CONSTRAINT "summaries_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "questions" ADD CONSTRAINT "questions_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "question_options" ADD CONSTRAINT "question_options_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "user_answers" ADD CONSTRAINT "user_answers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "user_answers" ADD CONSTRAINT "user_answers_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "user_answers" ADD CONSTRAINT "user_answers_selected_option_id_fkey" FOREIGN KEY ("selected_option_id") REFERENCES "public"."question_options"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "user_question_progress" ADD CONSTRAINT "user_question_progress_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "user_question_progress" ADD CONSTRAINT "user_question_progress_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "extension_tokens" ADD CONSTRAINT "extension_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

DO $$ BEGIN
    ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint

-- ============================================================================
-- ORIGINAL MIGRATION: Modifications to bring schema to expected state
-- These are idempotent - on fresh DB tables are already correct, on production
-- they apply the changes that were needed at the time
-- ============================================================================

ALTER TABLE "extension_tokens" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "question_options" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "questions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "subscriptions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "summaries" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_answers" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_question_progress" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "videos" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_id_fkey";
--> statement-breakpoint
ALTER TABLE "extension_tokens" ALTER COLUMN "user_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "videos" ALTER COLUMN "user_id" DROP DEFAULT;--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "users" ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON "extension_tokens" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable insert for users based on user_id" ON "extension_tokens" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable users to view their own data only" ON "extension_tokens" CASCADE;--> statement-breakpoint
DROP POLICY IF EXISTS "Enable users to view their own data only" ON "users" CASCADE;
