CREATE TABLE "transcript_windows" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "transcript_windows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"video_id" bigint NOT NULL,
	"window_index" integer NOT NULL,
	"start_time" integer NOT NULL,
	"end_time" integer NOT NULL,
	"text" text NOT NULL,
	"embedding" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "transcript_windows_video_id_window_index_key" UNIQUE("video_id","window_index")
);
--> statement-breakpoint
ALTER TABLE "questions" ADD COLUMN "source_quote" text;--> statement-breakpoint
ALTER TABLE "questions" ADD COLUMN "source_timestamp" integer;--> statement-breakpoint
ALTER TABLE "transcript_windows" ADD CONSTRAINT "transcript_windows_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "idx_transcript_windows_video_id" ON "transcript_windows" USING btree ("video_id");