CREATE TABLE "review_progress" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "review_progress_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"reviewable_item_id" bigint NOT NULL,
	"box_level" integer DEFAULT 1 NOT NULL,
	"next_review_date" date,
	"times_correct" integer DEFAULT 0 NOT NULL,
	"times_incorrect" integer DEFAULT 0 NOT NULL,
	"last_reviewed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "review_progress_user_reviewable_item_key" UNIQUE("user_id","reviewable_item_id")
);
--> statement-breakpoint
CREATE TABLE "reviewable_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reviewable_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" uuid NOT NULL,
	"item_type" text NOT NULL,
	"question_id" bigint,
	"flashcard_id" bigint,
	"video_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "reviewable_items_question_id_key" UNIQUE("question_id"),
	CONSTRAINT "reviewable_items_flashcard_id_key" UNIQUE("flashcard_id")
);
--> statement-breakpoint
ALTER TABLE "flashcards" ADD COLUMN "updated_at" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "review_progress" ADD CONSTRAINT "review_progress_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "review_progress" ADD CONSTRAINT "review_progress_reviewable_item_id_fkey" FOREIGN KEY ("reviewable_item_id") REFERENCES "public"."reviewable_items"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviewable_items" ADD CONSTRAINT "reviewable_items_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviewable_items" ADD CONSTRAINT "reviewable_items_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviewable_items" ADD CONSTRAINT "reviewable_items_flashcard_id_fkey" FOREIGN KEY ("flashcard_id") REFERENCES "public"."flashcards"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "reviewable_items" ADD CONSTRAINT "reviewable_items_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "idx_review_progress_user_id" ON "review_progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_review_progress_next_review_date" ON "review_progress" USING btree ("next_review_date");--> statement-breakpoint
CREATE INDEX "idx_reviewable_items_user_id" ON "reviewable_items" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_reviewable_items_video_id" ON "reviewable_items" USING btree ("video_id");