CREATE TABLE "study_sets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "study_sets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"source_type" text NOT NULL,
	"video_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "study_sets_public_id_key" UNIQUE("public_id"),
	CONSTRAINT "study_sets_source_type_check" CHECK (source_type IN ('video', 'manual', 'pdf'))
);
--> statement-breakpoint
ALTER TABLE "flashcards" ALTER COLUMN "video_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "questions" ALTER COLUMN "video_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "reviewable_items" ALTER COLUMN "video_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "reviewable_items" ADD COLUMN "study_set_id" bigint;--> statement-breakpoint
ALTER TABLE "study_sets" ADD CONSTRAINT "study_sets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "study_sets" ADD CONSTRAINT "study_sets_video_id_fkey" FOREIGN KEY ("video_id") REFERENCES "public"."videos"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "idx_study_sets_user_id" ON "study_sets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_study_sets_video_id" ON "study_sets" USING btree ("video_id");--> statement-breakpoint
ALTER TABLE "reviewable_items" ADD CONSTRAINT "reviewable_items_study_set_id_fkey" FOREIGN KEY ("study_set_id") REFERENCES "public"."study_sets"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "idx_reviewable_items_study_set_id" ON "reviewable_items" USING btree ("study_set_id");