CREATE TABLE "battle_game_answers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "battle_game_answers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"room_id" bigint NOT NULL,
	"slot_id" bigint NOT NULL,
	"question_id" bigint NOT NULL,
	"question_index" integer NOT NULL,
	"selected_option_id" bigint,
	"is_correct" boolean NOT NULL,
	"answered_at" timestamp with time zone NOT NULL,
	"score" integer NOT NULL,
	CONSTRAINT "battle_game_answers_slot_room_question_key" UNIQUE("slot_id","room_id","question_index")
);
--> statement-breakpoint
CREATE TABLE "battle_room_slots" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "battle_room_slots_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"room_id" bigint NOT NULL,
	"slot_index" integer NOT NULL,
	"slot_type" text DEFAULT 'empty' NOT NULL,
	"user_id" uuid,
	"bot_name" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "battle_room_slots_room_id_slot_index_key" UNIQUE("room_id","slot_index"),
	CONSTRAINT "battle_room_slots_slot_type_check" CHECK (slot_type IN ('empty', 'player', 'bot', 'locked'))
);
--> statement-breakpoint
CREATE TABLE "battle_rooms" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "battle_rooms_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
	"host_user_id" uuid NOT NULL,
	"study_set_id" bigint NOT NULL,
	"name" text NOT NULL,
	"visibility" text NOT NULL,
	"password_hash" text,
	"status" text DEFAULT 'waiting' NOT NULL,
	"time_limit_seconds" integer NOT NULL,
	"question_count" integer NOT NULL,
	"current_question_index" integer,
	"current_question_started_at" timestamp with time zone,
	"question_ids" integer[],
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "battle_rooms_public_id_key" UNIQUE("public_id"),
	CONSTRAINT "battle_rooms_visibility_check" CHECK (visibility IN ('public', 'private')),
	CONSTRAINT "battle_rooms_status_check" CHECK (status IN ('waiting', 'in_game', 'finished'))
);
--> statement-breakpoint
ALTER TABLE "battle_game_answers" ADD CONSTRAINT "battle_game_answers_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."battle_rooms"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "battle_game_answers" ADD CONSTRAINT "battle_game_answers_slot_id_fkey" FOREIGN KEY ("slot_id") REFERENCES "public"."battle_room_slots"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "battle_game_answers" ADD CONSTRAINT "battle_game_answers_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "battle_game_answers" ADD CONSTRAINT "battle_game_answers_selected_option_id_fkey" FOREIGN KEY ("selected_option_id") REFERENCES "public"."question_options"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "battle_room_slots" ADD CONSTRAINT "battle_room_slots_room_id_fkey" FOREIGN KEY ("room_id") REFERENCES "public"."battle_rooms"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "battle_room_slots" ADD CONSTRAINT "battle_room_slots_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "battle_rooms" ADD CONSTRAINT "battle_rooms_host_user_id_fkey" FOREIGN KEY ("host_user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "battle_rooms" ADD CONSTRAINT "battle_rooms_study_set_id_fkey" FOREIGN KEY ("study_set_id") REFERENCES "public"."study_sets"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
CREATE UNIQUE INDEX "battle_room_slots_user_id_unique" ON "battle_room_slots" USING btree ("user_id") WHERE user_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_battle_rooms_host_user_id" ON "battle_rooms" USING btree ("host_user_id");--> statement-breakpoint
CREATE INDEX "idx_battle_rooms_status" ON "battle_rooms" USING btree ("status");